### ISSUE TITLE
Feature: User can view list of recipes

### ISSUE THREAD

**Issue by Kasiett** [Kasiett/recipes#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the list of all available recipes and user can sort by types for ex: salads , drinks, etc.

## 📐 Functionality
User can go to main page and view list of recipes 
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="208" alt="Screenshot 2023-06-09 at 4 41 26 PM" src="https://github.com/Kasiett/recipes/assets/64724132/37fc1d92-f741-413c-9b2b-f3047d0b15be">

<img width="205" alt="Screenshot 2023-06-09 at 4 44 14 PM" src="https://github.com/Kasiett/recipes/assets/64724132/c77e045f-cebe-4d80-80e9-664a1e9e1dc8">
<img width="613" alt="Screenshot 2023-06-12 at 12 14 32 PM" src="https://github.com/Kasiett/recipes/assets/64724132/82a9b117-4c09-4799-baa5-86e711c60d7b">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to  recipes database 
- [x] Update `data.sql` to recipes table with mock data

### ☁️ Server Tasks

- [x] Update `server.js` handle GET  endpoint    for **api/recipes**
- [x] Update `server.js` handle POST endpoint  for **api/recipes** 
- [x] Update `server.js` handle DELETE endpoint  for **api/recipes** 
- [x] Update `server.js` handle UPDATE endpoint  for **api/recipes** 
- [x] Test with HTTPie all above endpoints
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render Header Recipes 
- [x] Create a component to render Footer Recipes 
- [x] Create a component to render  Recipes List
- [x] Create a component to render Recipes item 

> 1. title, 
>  2. image,
>  3. description, 
>  4. rating, 
>  5. liking, 
> 6. commenting, 
>  7. adding to fav

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
